site_name: httpx-aiohttp
repo_url: https://github.com/karpetrosyan/httpx-aiohttp
repo_name: GitHub

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Introduction: index.md
  - Compatibility: compatibility.md
  - httpx2 support: httpx2.md
  - How it works: how_it_works.md
  - How it's tested?: how_its_tested.md
  - Why?: why.md
