name: publish
on: workflow_dispatch

permissions:
  contents: write

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest

    env:
      HTTPX_AIOHTTP_PYPI: ${{ secrets.HTTPX_AIOHTTP_PYPI }}

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      - name: "Build"
        run: "uv build"
      - name: "Publish"
        run: "./scripts/publish"
